name: Auto Revalidate Blog

on:
  schedule:
    # 매 시간마다 실행
    - cron: '0 * * * *'
  workflow_dispatch: # 수동 실행 가능

jobs:
  revalidate:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger revalidation
        run: |
          curl -X GET "${{ secrets.SITE_URL }}/api/revalidate?secret=${{ secrets.REVALIDATION_SECRET }}"
          echo "Blog revalidated at $(date)"